### ISSUE TITLE
Die App verlangt nach dem genauen Standort / The app requests the exact location

### ISSUE THREAD

**Issue by Livermoriu** [marq24/UUID0xFD6FTracer#13]
Hallo,
die App verlangt ein aktivierten genauen Standortdienst mit GPS.
Wenn der unter LineageOS sogenannter Energiesparmodus vom Standort aktiviert ist, werden statt GPS nur noch WLAN, Bluetooth und Mobilfunk zugelassen.
Die „Corona Tracing“ App von F-Droid scheint damit auch problemlos zu funktionieren.
Fehlt in der Scanner App nur die Unterscheidung vom genauen und ungenauen Standort oder lässt sich das nicht anders lösen und GPS muss an sein?
Mir ist bewusst dass, unabhängig davon welcher Standortdienst aktiviert ist, von der App nicht darauf zugegriffen wird. Danke dafür.

**Comment by marq24** [comment]
Moinsen!

DANKE für den Hinweis - ich habe jetzt gerade einen neue Version released - https://github.com/marq24/UUID0xFD6FTracer/releases/tag/0.9.1.16 - in der man über die "Experten Einstellung" konfigurieren kann, ob nehmen dem GPS-LocationProvider auch noch alternative (network, passive & fuse) zugelassen werden.

Die Herausforderung für mich ist, dass ich selbst viel zu wenig unterschiedliche Hardware besitze um die ganzen OS-Varianten abzufrühstücken (LameDeveloperExcuse) - es KANN also gut sein, dass diese Neue Version noch immer nicht das tut, was Du erwartest - dann muss ich ggf. ganz auf die Prüfung verzichten... Es ist sowieso für mich total überraschend gewesen, dass der BTLE-Scanner nur dann funktioniert, wenn gleichzeitig auch ein/der LocationDienst aktiviert ist.

Ich bin auf Dein Feedback gespannt!

**Comment by Livermoriu** [comment]
Hallo,
danke für die schnelle Reaktion, die Änderung scheint zu funktionieren und die Aufforderung wird nicht mehr angezeigt.
Leider habe ich aktuell keine anderen CoronaWarn Apps in der Umgebung um den Scanner zu testen. Der steht verständlicher Weise aktuell bei 0 Treffer, nächste Woche könnte ich das prüfen.
Wie lange dauert es eigentlich im Schnitt bis eine neue Version im F-droid auftaucht?
Deine App ist übrigens die erste, von ein paar getesteten Apps, die auf meinen google-freien Smartphone funktioniert.

**Comment by marq24** [comment]
Wie lange das bei F-droid dauert, kann ich Dir leider nicht sagen -hier fehlt mir einfach die Erfahrung (das hier ist auch mein erste Projekt dieser Art)...

Und wie gesagt, es ist SEHR gut möglich, dass mit den LocationProvidern 'Network' und oder 'Passiv' der BTLE-Scanner vom OS überhaupt nicht funktioniert (also niemals BTLE-Beacons gefunden werden) - also wenn Du "nie wieder" einem CoronaWarnApp über den Weg läufst, dann wird das wohl daran liegen, dass der Scanner nicht arbeitet.

**Comment by Livermoriu** [comment]
Erfolg, ich konnte die App heute noch mal testen und der Scanner hat einwandfrei funktioniert.

**Comment by marq24** [comment]
cool! - thanks for the feedback
