### ISSUE TITLE
Widget? 

### ISSUE THREAD

**Issue by Teonash65** [marq24/UUID0xFD6FTracer#14]
Die App funktioniert einwandfrei auf meinem Galaxy S10 Lite.
Wäre es möglich, ein einfaches Widget dazu zu erstellen?

Vielen Dank!

**Comment by marq24** [comment]
möglich wäre das sicherlich - allerdings habe ich sowas noch nie versucht - ich selbst verwende gar keine (also Widgets) - ist das denn nicht mit der Notification nicht schon "always visible" genug?

**Comment by Teonash65** [comment]
Hallo und vielen Dank für die schnelle Antwort.
Prinzipiell ja, schön wäre es dennoch, da in einem Widget eine größere Schrift möglich wäre und beim Entsperren gleich die Anzahl der Sender zu erkennen wäre. 
War nur so ein Gedanke. 

Wünsche noch ein gesundes neues Jahr!

**Comment by marq24** [comment]
Also wenn ich mein Telefon aktiviere (also nicht entsperre), sehe ich sofort die Notification, und die Anzahl der aktiven Sender [gefunden: X]... Ist das bei Dir anders? Ein Widget sehe ich je erst nach dem Entsperren des Geräts...  Für mich ist die Info (aktive Sender) beim aktivieren des Displays zu sehen (ich wiederhole mich)... 

Ich kann mir das mit dem "Widget" ja mal ansehen - kann ja auch nicht so kompliziert sein - aktuell hänge ich aber noch in meinem GPSLogger an einer optimierung fest... dass zieht sich noch ne Weile... Du kannst aber ggf so gut sein und mal einen Entwurf (auf Papier?) machen, wie Du Dir das Layout von dem Widget vorstellst...

Und Danke für die wünsche,,, Möge die Impfung auch bald für uns kommen...

**Comment by Teonash65** [comment]
Alles gut. Ist nicht unbedingt notwendig.

Für die Anzahl der Sender muss ich allerdings die Benachrichtigungsleiste erst herunter ziehen.

Vielleicht gibt es ja auch eine Möglichkeit, sich ein Widget mittels KWGT zu basteln.

**Comment by marq24** [comment]
auch wenn's quasi schon fast OT ist... so sieht das bei mir nach dem Bildschirm aktivieren aus...
![image](https://user-images.githubusercontent.com/8012359/103467006-c00e1880-4d4a-11eb-9769-ea3ca9ea051c.png) - Du hast da nur 'Hintergrund Tracing Dienst' stehen?

**Comment by Teonash65** [comment]
Okay, mein Fehler.
Wenn ich die Details der Benachrichtigungen auf den Sperrbildschirm einschalte, sehe ich die Anzahl auch.
Vielen Dank!
