### ISSUE TITLE
Document that packets of the same device are also detected

### ISSUE THREAD

**Issue by ChristianKurz** [marq24/UUID0xFD6FTracer#15]
The app also detects packets sent out by the corona app running on the same device. This should be mentioned in the readme.

**Comment by marq24** [comment]
Hi Christian,

bislang ist mir kein Telefon/OS in die Finger gekommen, bei der der BluetoothScanner (des OS) die Beacons die das Gerät selbst aussendet als "gefundene" Geräte in der Umgebung zurückliefert...

Wenn dies bei Dir der Fall ist, dann wäre ich sehr Neugierig, auf welchem OS/Gerät Du dieses Phänomen beobachtest... Denn irgendwie ist es schon klar, das die App "sich selbst" nicht mitzählen sollte...

**Comment by ChristianKurz** [comment]
Ich habe nun festgestellt, dass es wohl nur ein zufall war. Die anzahl der erkannten geräte änderte sich jedes mal wenn ich die eigene app an und aus schaltete.
Ohne andere empfangene geräte werden aber auch meine pakete nicht angezeigt.
