### ISSUE TITLE
0xDF6F or 0xFD6F?

### ISSUE THREAD

**Issue by PlutoEventHorizon** [marq24/UUID0xFD6FTracer#17]
In the settings window there are two different UUIDs. The first one is below "Länder (UUIDs) UUID 0xDF6F [...]" and the second one is below "Framework basiert (UUID 0xFD6F)". Are there different UUIDs? I'm not familiar with this.

![UUID_0xFD6F_Scanner](https://user-images.githubusercontent.com/72520053/104855600-971e8380-5905-11eb-9a66-429e14a48e73.png)

**Comment by marq24** [comment]
France have made the decision not to use the ContactTracingFramework provided by Apple & Google and made a own implementation - so the France-App use a different UUID... 

So it's a "All Countries that make use of the Framework provided by Google and Apple" and/or "France"

**Comment by marq24** [comment]
... btw. - pressing the "Länder" thing will give you a selection which UUID(s) you would like to trace [not sure if you have tried that yet]

**Comment by PlutoEventHorizon** [comment]
> ... btw. - pressing the "Länder" thing will give you a selection which UUID(s) you would like to trace [not sure if you have tried that yet]

Thank you. I didn't know that.

0xFD and 0xDF isn't a typo with F and D? The app name ist UUID 0x**FD**6F. In the app you switch D and F to 0x**DF**6F? Why?

**Comment by marq24** [comment]
Thanks! Yes that's a typo... it should be always/everywhere FD (and not DF)... I'll fix that ASAP

**Comment by marq24** [comment]
fix is available in 0.9.1,17 - nochmal DANKE!
