### ISSUE TITLE
Playstore

### ISSUE THREAD

**Issue by Citro12** [marq24/UUID0xFD6FTracer#2]
Hallo,
unter welchem Namen ist der Tracer der neuen Version im Google Playstore zu finden ? Finde ich leider nicht. 

Viele Grüße

**Comment by marq24** [comment]
leider **noch** immer nicht - 36h scheinen zu kurz zu sein - wenn er überhaupt die Google-Support-Hürde nimmt - sobald der '*Beacon UUID 0xFD6F Scanner*' (so ist dann der Name im PlayStore) tatächlich verfügbar ist, werde ich die DL' links hier auf Githib einpflegen... (auch wenn wir das alles schonmal hatten) *seuftz*

**Comment by marq24** [comment]
Seit gestern ist er wieder im Store verfügbar
https://play.google.com/store/apps/details?id=com.emacberry.uuid0xfd6fscan

**Comment by marq24** [comment]
und da isse auch schon wieder gesperrt - was für elende PENNER!

![image](https://user-images.githubusercontent.com/8012359/87472927-05198380-c621-11ea-8f31-1e618d6b329c.png)
