### ISSUE TITLE
Ignorierte Sender

### ISSUE THREAD

**Issue by Citro12** [marq24/UUID0xFD6FTracer#21]
Hallo, bei der App werden öfters ignorierte Geräte/devices angezeigt. Ab wieviel dbm geschieht das ? Über -100dbm ? Den Nahbereich habe ich auf -63dbm eingestellt, laut CWA ist der Nahbereich zwischen -55 und -73 dbm.

Grüße

**Comment by marq24** [comment]
Wenn ich da meinen eigenen Code richtig verstehe geht das grouping des Signals ab hier los: https://github.com/marq24/UUID0xFD6FTracer/blob/d351117a68d43e7f5a5fc8ce41ee48e43c139e6d/app/src/main/java/com/emacberry/uuid0xfd6fscan/ScannerService.java#L490

Wenn Du bestimmte Geräte (ab -100dbm) nicht sehen möchtest, dann "Schwellenwert verwenden EIN" und dann den Wert angeben (oder den default lassen)...

**Comment by Citro12** [comment]
Hallo,der voreingestellte Wert für Nah beträgt -82 dbm, für Mittel -90dbm. Das erschien mir zu schlecht und stellte um auf -63für nah und -73 für mittel. Ist das OK ? Ignoriert heißt jene unter der Schwelle von voreingestellt in der App von -98dbm ?--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 05.08.21, 13:57 schrieb marq24 ***@***.***>:

   
  Wenn ich da meinen eigenen Code richtig verstehe geht das grouping des Signals ab hier los: https://github.com/marq24/UUID0xFD6FTracer/blob/d351117a68d43e7f5a5fc8ce41ee48e43c139e6d/app/src/main/java/com/emacberry/uuid0xfd6fscan/ScannerService.java#L490 
  Wenn Du bestimmte Geräte (ab -100dbm) nicht sehen möchtest, dann "Schwellenwert verwenden EIN" und dann den Wert angeben (oder den default lassen)...

**Comment by Citro12** [comment]
Hallo,der voreingestellte Wert für Nah beträgt -82 dbm, für Mittel -90dbm. Das erschien mir zu schlecht und stellte um auf -63für nah und -73 für mittel. Ist das OK ? Ignoriert heißt jene unter der Schwelle von voreingestellt in der App von -98dbm ?-

**Comment by marq24** [comment]
entschuldige die späte Antwort... 

Das mit den Signalstärken ist wirklich knifflig - bzw man muss sich da selsbt für was entscheiden... die iFöns die hier rumliegen senden ein soviel stärkeres Signal als meine Android Systeme, dass es mir da wirklich sehr schwer fällt eine pauschaue aussage zu tätigen... 

Also wenn ein iPhone11 und and Pixel3 neben einander liegen, dann kommen auf dem UUIDTracer der sich in 5m Entfernung befindet total unterschiedliche Signalstärken der beiden Telefone an... Wenn man dann noch eins der Telefone in eine (Hosen)tasche steckt wirds noch "zufälliger"... also gerade die Frage des Trashholds (wann ignoriere ich einfach) ist für mich als Einzelperson nicht zu ermitteln... Sorry für die WischiWaschi-Antwort

**Comment by Citro12** [comment]
Hi, alles gut, ich habe auch schon bemerkt, dass ein S10 derart schwach sendet, dass man so gut wie nie ein positives Ergebnis über die CWA bekommen könnte
