### ISSUE TITLE
Make unfiltered number of BLE visible

### ISSUE THREAD

**Issue by basilstotz** [marq24/UUID0xFD6FTracer#3]
This would allow to estimate the share of Covid-Apps out of all Devices (with BLE on)

**Comment by marq24** [comment]
I do not believe, that counting total number of visible 'other' BluetoothLE Devices will add much value - have in mind, that every single Bluetooth headset, smart watches and other gadgets (like HR Sensors) might be all be discovered/visible.

And I do not see a way to filter "just phones"... which you would probably like to know... (and have a share of #phones/#UUID 0xFD6F Beacons)

**Comment by basilstotz** [comment]
OK. You're right. I was neglecting other, non smartphone, BLE devices.

**Comment by marq24** [comment]
Actually what you like to archive is some sort of head count ;-) - that's reasonable for me - ut for sure going way beyond my capabilities. I'll hope it's ok, when I close this one.
