### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Citro12** [marq24/UUID0xFD6FTracer#5]
Wird es die App über F-Droid geben ? Wegen der Umbenennung

Grüße

**Comment by marq24** [comment]
Ich arbeite daran ;-)
https://gitlab.com/fdroid/rfp/-/issues/1423#note_380266525

**Comment by TPS** [comment]
This is just now available via [F-droid](https://f-droid.org/app/com.emacberry.uuid0xfd6fscan), so a link (better, [an image button](https://commons.m.wikimedia.org/wiki/File:Get_it_on_F-Droid.svg) like you've for Amazon Appstore) would be an awesome addition to the ReadMe.

**Comment by marq24** [comment]
doku is update - I hope it's fine to close this

**Comment by Citro12** [comment]
Prima, es ist aber noch die Vorversion in F-Droid zu bekommen

**Comment by marq24** [comment]
noch habe ich keine "Ahnung" ob sich F-Droid dann einfach die neue Version automatisch zieht - die 0.9.7 Version ist ja auch erst von Gestern...
