### ISSUE TITLE
Support for 0xFD64 (french StopCovid app)

### ISSUE THREAD

**Issue by weather-kr** [marq24/UUID0xFD6FTracer#6]
Currently the App only supports the Service 0xFD6F, which is used by Google/Apple API

The french StopCovid APP uses a different Beacon Service:

"0000fd64-0000-1000-8000-00805f9b34fb"

For visitors in France or in areas next to country borders it might be useful to see how many users are using the french app instead or in addition to the local app based on the Exposure Notification API

I myself scanned BLE Beacons from both StopCovid/France and CWA/Germany APP with my raspberry PI and there the advantage of CWA is obvious. The french app only sends Beacons while running in foreground on Iphone. The CWA app also sends the Beacons while running in background.

**Comment by marq24** [comment]
would you mind to provide a france translation of the stings used in return ? :-D

I would need translations for:

```
    <string name="notifyChannelBase">Core Service</string>
    <string name="app_service_title">Background Tracer Service</string>
    <string name="app_service_msgOff">Please start Scanner</string>
    <string name="app_service_msgOffNoPermissions">Please start the App in order to restart the Scanner</string>

    <string name="app_service_msgScan1">Scanning Environment&#8230;</string>
    <string name="app_service_msgScan2">[found: %1$d]</string>

    <string name="menu_finish">Close App</string>
    <string name="menu_exit">Terminate Service</string>
    <string name ="menu_exit_notify_action">EXIT</string>
    <string name ="menu_start_notify_action">Start Scan</string>
    <string name ="menu_stop_notify_action">Stop Scan</string>

    <string name ="act_active_beacons">Active Beacons: %1$d</string>
    <string name="menu_start">Start Scan Service</string>
    <string name="menu_stop">Stop Scan Service</string>

    <string name="menu_settings">Settings&#8230;</string>

    <string name="pref01_TITLE">Settings</string>
    <string name="pref01_AUTOSTART_TITLE">Service Autostart</string>
    <string name="pref01_AUTOSTART_OFF">OFF</string>
    <string name="pref01_AUTOSTART_ON">ON - The \'Background Tracer Service\' will be automatically started after a device reboot (after successful login)</string>

    <string name="pref01_SCANMODE_TITLE">Country\'s</string>
    <string-array name="pref01_SCANMODE_ENTRIES">
        <item name="01">Germany (CoronaWarnApp)</item>
        <item name="02">France (StopCovid)</item>
        <item name="03">France (StopCovid) and Germany (CoronaWarnApp)</item>
    </string-array>
```

**Comment by marq24** [comment]
Please check/verify, if the new build https://github.com/marq24/UUID0xFD6FTracer/releases/tag/0.9.1.4 will work as expected - I just have tested with CoronaWarnApp - and this still works.

If you update you need to enable StopCoid Support via the Settings - if you make a fresh install and you are running Android with French language, then StopCovid is auto-enabled.

Also PLEASE be so kind and review my "Google Translate based" French translation!
https://github.com/marq24/UUID0xFD6FTracer/blob/master/app/src/main/res/values-fr/strings.xml

**Comment by weather-kr** [comment]
Thank you.

The App counts the french BLE Senders as expected. I have run a test with two IPhone 5s counterparts where the french app was installed. 

Sometimes the app shows 3 senders for a short time when only 2 are expected, most probably this happens after MAC Address change.

I am a german user and my french language skill is only very basic.
