### ISSUE TITLE
Einstellungen

### ISSUE THREAD

**Issue by Citro12** [marq24/UUID0xFD6FTracer#7]
Hallo,
welche Covid-Apps und welche Länder ausser Frankreich umfassen die Suche in den Einstellungen 1 und 3 der neuen Version 0.9.1.5 ?

Danke für die großartige App

Grüße

**Comment by marq24** [comment]
tut mir leid das eine Antwort so lange auf sich warten lässt... Also ich habe da jetzt mit einer Erweiterung der Doku angefangen... GGF war es auch nicht schlau das ganze "Länder" zu nennen...

https://github.com/marq24/UUID0xFD6FTracer/blob/master/SETTINGS.md

helfen Dir diese Info's?

**Comment by Citro12** [comment]
Super, vielen Dank für die Info :)

**Comment by marq24** [comment]
ist wohl erledigt - die Infos sind jetzt auch in der App selbst (settings)
